export const dummy=[
    {
      name: 'Laboratory',
      link:'',
    submenu: [
      {
        name: 'Masters',
        link:'',
        childmenu: [
          { name: 'Company',link:'', },
          { name: 'Gepgraphical Area',link:'', },
          { name: 'Facility',link:'', },
          {
            name: 'Generic',
            link:'lis/generic-master'
           },
          { name: 'Lab Department' ,link:'',},
          { name: 'Test/Service' ,link:'',},
          { name: 'Location' ,link:'',},
          { name: 'Organism' ,link:'lis/organism-master',},
          { name: 'Antibiotic Panel' ,link:'',},
          { name: 'Doctor' ,link:'',},
          { name: 'Help' ,link:'',},
          { name: 'Print Queue' ,link:'',},
          { name: 'Stains' ,link:'',},
          { name: 'Barcode' ,link:'',},
          { name: 'Service Group' ,link:'',},
          { name: 'Credit Company' ,link:'',},
          { name: 'Service Rate' ,link:'',},
        ],
      },
      {
        name: 'Security', link:'',childmenu: [
          { name: 'User Access' ,link:'',},
          { name: 'Test Authorization Setup' ,link:'',},
          { name: 'Group Access' ,link:'',},
          { name: 'Change Password' ,link:'',},
          { name: 'Themes' ,link:'',},
          { name: 'Stylesheet Creation' ,link:'',},
        ],
      },
      {
        name: 'Accession',link:'', childmenu: [
          { name: 'Lab Reception' ,link:'',},
          { name: 'Accession Barcode' ,link:'lis/accession-barcode',},
          { name: 'Modify Accession' ,link:'',},
          { name: 'Edit Patient Dempgraphics' ,link:'',},
          { name: 'Extra Barcode' ,link:'',},
          { name: 'Thinprep' ,link:'',},
          { name: 'OPD Reception' ,link:'',},
          { name: 'OPD' ,link:'',},
          { name: 'Phlebotomy' ,link:'',},
          { name: 'Sample Verification at OPD' ,link:'',},
          { name: 'Pending Profiles at OPD' ,link:'',},
          { name: 'Sample Acceptance at OPD' ,link:'',},
          { name: 'Histo Accession' ,link:'',},
          { name: 'PCR Accession' ,link:'',},
        ],
      },
      {
        name: 'Sample Handling',link:'', childmenu: [
          { name: 'Sample Collection' ,link:'',},
          { name: 'Breakup of Histopathology' ,link:'',},
          { name: 'Loan of Samples' ,link:'',},
          { name: 'Return of Samples' ,link:'',},
          { name: 'Sample Status' ,link:'',},
          { name: 'Sample Collection from HIS' ,link:'',},
          { name: 'Sample Status Immunology' ,link:'',},
          { name: 'Patient History' ,link:'',},
          { name: 'Doctor Instruction' ,link:'',},
          { name: 'Sample Collection at OPD' ,link:'',},
          { name: 'Rejection Cancellation' ,link:'',},
          { name: 'Reject Sample' ,link:'',},
          { name: 'Patient Portal' ,link:'',},
          { name: 'Sample Acknowledgement' ,link:'',},
          { name: 'Histo Sample Collection from HIS' ,link:'',},
        ],
      },
      {
        name: 'Departmental Work', link:'',childmenu: [
          { "name": "Creation of Packing List" ,link:'',},
          { "name": "Work Assignment" ,link:'',},
          { "name": "Mark Work Completion" ,link:'',},
          { "name": "Mark Sample for Re-run" ,link:'',},
          { "name": "Receive Results of Tests" ,link:'',},
          { "name": "Merge Patient ID" ,link:'',},
          { "name": "View Work Assignment" ,link:'',},
          { "name": "Update Civil ID" ,link:'',},
          { "name": "Query Builder" ,link:'',},
          { "name": "Patient Record Summary" ,link:'',},
          { "name": "Infection Control" ,link:'',},
          { "name": "Query Builder for Histo" ,link:'',},
          { "name": "Creation of Packing List (Barcode)" ,link:'',},
          { "name": "Update New Civil ID",link:'', }
        ]
      },
      { name: 'Reporting', link: '' },
      { name: 'Isofplex', link: '' },
      { name: 'Control', link: '' },
      { name: 'Blood Bank', link: '' },
      { name: 'Reports', link: '' },
      { name: 'Maintainance', link: '' },
      { name: 'Inventory', link: '' },
      { name: 'Others', link: '' },
      { name: 'Toxicology', link: '' },
      { name: 'Histopathology Ops', link: '' },
    ]
  },    
  ];